name       : python-owslib
version    : 0.16.0
release    : 3
source     :
    - https://github.com/geopython/OWSLib/archive/0.16.0.tar.gz : 700d96e13298916089b8d05a08a6533e0fab85f34c2dc22fd88b57e37ef320fa
license    : BSD-3-Clause
component  : programming.python
summary    : Client library for OGC web services
description: |
    OWSLib is a Python package for client programming with Open Geospatial Consortium (OGC) web service (hence OWS) interface standards, and their related content models.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-dateutil
    - python-pyproj
    - python-pytz
    - python-requests
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
