name       : python-owslib
version    : 0.15.0
release    : 1
source     :
    - https://github.com/geopython/OWSLib/archive/0.15.0.tar.gz : 3a0cb567ffa8a574991feb686ea1f2d3f9054ea0e625bcd25f7747f63f88d5ea
license    : BSD 3-clause
component  : programming.python
summary    : Client library for OGC web services
description: |
    OWSLib is a Python package for client programming with Open Geospatial Consortium (OGC) web service (hence OWS) interface standards, and their related content models.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-dateutil
    - python-pyproj
    - python-pytz
    - python-requests
setup      : |
    cp -a . ../py3build
    mv $PWD ${PWD%/*}/py2build
build      : |
    pushd py2build
    %python_setup
    popd

    pushd py3build
    %python3_setup
    popd
install    : |
    pushd py2build
    %python_install
    popd

    pushd py3build
    %python3_install
    popd
